---
openapi: 3.0.0
info:
  title: ml-microservice-api
  description: The API for the ML Microservice
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/AUDREYELIM_1/MLMicroservice/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /predict:
    get:
      tags:
      - Predict
      description: Get the ranking of a student (the output of the ML microservice) as a score between 0-20 as a function of the input features
      operationId: getPrediction
      parameters:
      - name: studyTime
        in: query
        description: time spent studying
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: reason
        in: query
        description: reason for pursuing a higher education
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: activities
        in: query
        description: whether they have any extracurriculars
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: absences
        in: query
        description: number of absences
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: higher
        in: query
        description: whether they want a higher education
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: traveltime
        in: query
        description: time spent commuting to school
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: failures
        in: query
        description: number of classes failed
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: Dalc
        in: query
        description: daily alcohol consumption
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: Walc
        in: query
        description: weekend alcohol consumption
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Student ranking
          content:
            application/json:
              schema:
                type: integer
                format: int32
        "500":
          description: Server failure
        "400":
          description: Client failure
  /getDecision:
    get:
      tags:
      - GetDecision
      description: give a "yes" or "no" decision on whether a candidate should be admitted
      operationId: add
      parameters:
      - name: id
        in: query
        description: Student id
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: score
        in: query
        description: score from predict
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: student decision is returned
          content:
            application/json:
              schema:
                type: string
        "400":
          description: client failure
        "500":
          description: server failure
components: {}
